stages: [build, test, release]

#include:
#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:commit-msg@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:composer:normalize@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:composer:psr-verify@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:composer:validate@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:eslint@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:json@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:php@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:stylelint@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:typoscript@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:xliff@$CI_COMMIT_SHA
#    inputs:
#      stage: build

#  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/lint:yaml@$CI_COMMIT_SHA
#    inputs:
#      stage: build

include:
  - component: ${CI_SERVER_HOST}/devops/ci-cd-components/release-tools/semantic-release@1.0.4
    inputs:
      stage: release

#create-release:
#  stage: release
#  image: registry.moselwal.io/devops/release-cli/release-cli:latest
#  rules:
#    - if: $CI_COMMIT_TAG
#  script: echo "Creating release $CI_COMMIT_TAG"
#  release:
#    tag_name: $CI_COMMIT_TAG
#    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"